---
- name: Installing MySQL
  apt:
    update_cache: yes
    cache_valid_time: 21600 # 6 hours.
    pkg: "{{ packages }}"
    state: present

- name: Configure MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Remove anonymous user account
  mysql_user:
    name: ""
    host: localhost
    state: absent

- name: Remove all anonymous user accounts
  mysql_user:
    name: ""
    host_all: yes
    state: absent

- name: Create a test user
  mysql_user:
    name: test
    password: test
    priv: '*.*:ALL'
    state: present

- name: Create a new database
  mysql_db:
    name: italy
    state: present

- name: Move mysql dump to managed host
  copy:
    src: italy.sql
    dest: /home/vagrant

- name: Restore database
  mysql_db:
    name: italy
    state: import
    target: /home/vagrant/italy.sql

